### ISSUE TITLE
Can't store ArrayLists

### ISSUE THREAD

**Issue by robisaks** [fdoyle/EasyDatastore#9]
```
@Preference("object")
ObjectEntry<List<MyModel>> myModels();
```

```
java.lang.ClassCastException: libcore.reflect.ParameterizedTypeImpl cannot be cast to java.lang.Class
     at com.lacronicus.easydatastorelib.DatastoreBuilder$DatastoreHandler.invoke(DatastoreBuilder.java:61)
     at java.lang.reflect.Proxy.invoke(Proxy.java:393)
     at $Proxy0.recentSets(Unknown Source)
```

**Comment by fdoyle** [comment]
Thanks for the heads up, fixed this for 1.0.4
